#!/usr/bin/perl

print <<EOT;
// generated by txt2c.pl from $ARGV[0]
#include <stdlib.h>
EOT

my %manuals = map { /manual-?([^.]*)/ or die; (lc($1) || 'en') => $_ } glob('manual*txt');

for my $lang (sort keys %manuals) {
    my $name, $ifdef, $manual = $manuals{$lang};

    if ($lang eq 'en') {
        # Some languages don't have translated manuals yet, so use English
        my @langs = grep { !exists $manuals{$_} } map { /-([^.]*)/ or die; lc $1 } glob('lang-*.txt');
        push @langs, 'en';
        
        my $cond = join ' || ', map { "defined(LDLANG_" . uc($_) . ")" } sort @langs;
        
        $name = "HelpText";
        $ifdef = "#if $cond";
    } else {
        $name = "HelpText" . ucfirst $lang;
        $ifdef = "#ifdef LDLANG_" . uc $lang;
    }

    print <<EOT;
$ifdef
char *$name\[] = {
EOT

    open(IN, $manual) or die;
    while(<IN>) {
        chomp;
        s/\\/\\\\/g;
        s/"/\\"/g;

        print qq{    "$_",\n};
    }
    close IN;

    print <<EOT;
    NULL
};
#endif

EOT

}
